Repository AY2223S1-CS2103T-W15-3/tp, pull requests merged in 2022-09, with the labels that each got.

#18 Modify PPP link
  docs/AboutUs.md
  docs/team/jiacheng-y.md
Labels: priority.Medium

#41 Update User Guide features: listi and findi
  docs/UserGuide.md
Labels: priority.High, type.Task

#46 Update UG: Quick start, addi, deletei
  docs/UserGuide.md
Labels: type.Task

#48 Update use cases in Developer Guide
  docs/DeveloperGuide.md
Labels: priority.High, type.Task
