Repository AY2223S1-CS2103T-W15-3/tp, pull requests merged in 2022-10, with the labels that each got.

#57 Implement delete orders
  src/main/java/tracko/commons/core/Messages.java
  src/main/java/tracko/logic/commands/order/DeleteOrderCommand.java
  src/main/java/tracko/logic/parser/TrackOParser.java
  src/main/java/tracko/model/Model.java
  src/main/java/tracko/model/ModelManager.java
  src/main/java/tracko/model/TrackO.java
  src/main/java/tracko/model/order/OrderList.java
  src/test/java/tracko/logic/commands/AddOrderCommandTest.java
  src/test/java/tracko/logic/commands/DeleteCommandTest.java
  src/test/java/tracko/logic/commands/DeleteOrderCommandTest.java
  src/test/java/tracko/logic/commands/EditCommandTest.java
  src/test/java/tracko/logic/parser/DeleteOrderCommandParserTest.java
  src/test/java/tracko/logic/parser/ParserUtilTest.java
  src/test/java/tracko/testutil/TypicalIndexes.java
Labels: priority.High, type.Story

#65 Fix bugs in addi command logic
  src/main/java/tracko/logic/commands/item/AddItemCommand.java
  src/main/java/tracko/logic/parser/item/AddItemCommandParser.java
Labels: type.Bug

#67 Add Storage support for Inventory items
  src/main/java/tracko/MainApp.java
  src/main/java/tracko/model/UserPrefs.java
  src/main/java/tracko/storage/JsonAdaptedItem.java
  src/main/java/tracko/storage/JsonSerializableTrackO.java
  src/main/java/tracko/storage/JsonTrackOStorage.java
  src/main/java/tracko/storage/Storage.java
  src/main/java/tracko/storage/StorageManager.java
  src/main/java/tracko/storage/TrackOStorage.java
  src/test/java/tracko/logic/LogicManagerTest.java
  src/test/java/tracko/storage/StorageManagerTest.java
Labels: priority.High, type.Task, severity.High

#70 Fix user guide tables and reflect new item fields in UG
  docs/UserGuide.md
Labels: priority.Low, type.Task, type.Bug, severity.Medium

#69 Add Ui support for inventory items
  src/main/java/tracko/ui/DisplayBox.java
  src/main/java/tracko/ui/ItemCard.java
  src/main/java/tracko/ui/ItemListPanel.java
  src/main/java/tracko/ui/MainWindow.java
  src/main/java/tracko/ui/OrderCard.java
  src/main/java/tracko/ui/OrderListPanel.java
  src/main/resources/view/DisplayBox.fxml
  src/main/resources/view/ItemListCard.fxml
  src/main/resources/view/ItemListPanel.fxml
  src/main/resources/view/MainWindow.fxml
Labels: priority.High, type.Task, severity.High

#72 Fix bug in reading items from json
  src/main/java/tracko/MainApp.java
  src/main/java/tracko/logic/Logic.java
  src/main/java/tracko/logic/LogicManager.java
  src/main/java/tracko/model/Model.java
  src/main/java/tracko/model/ModelManager.java
  src/main/java/tracko/model/UserPrefs.java
  src/main/java/tracko/ui/MainWindow.java
  src/test/java/tracko/logic/commands/AddOrderCommandTest.java
  src/test/java/tracko/model/ModelManagerTest.java
  src/test/java/tracko/storage/StorageManagerTest.java
Labels: type.Bug

#77 Fix UI display for findi
  src/main/java/tracko/logic/Logic.java
  src/main/java/tracko/logic/LogicManager.java
  src/main/java/tracko/model/ModelManager.java
  src/main/java/tracko/ui/MainWindow.java
Labels: type.Bug

#76 Fix application not loading items from JSON
  src/main/java/tracko/model/TrackO.java
Labels: type.Bug

#82 Implement UI for TrackO
  src/main/java/tracko/ui/CommandBox.java
  src/main/java/tracko/ui/DisplayBox.java
  src/main/java/tracko/ui/HelpWindow.java
  src/main/java/tracko/ui/ItemCard.java
  src/main/java/tracko/ui/ItemListPanel.java
  src/main/java/tracko/ui/OrderCard.java
  src/main/java/tracko/ui/OrderListPanel.java
  src/main/java/tracko/ui/ResultDisplay.java
  src/main/java/tracko/ui/StatusBarFooter.java
  src/main/java/tracko/ui/UiManager.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/ItemListCard.fxml
  src/main/resources/view/ItemListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/OrderListCard.fxml
  src/main/resources/view/OrderListPanel.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/TrackOTheme.css
Labels: priority.High

#84 Add edit item command
  src/main/java/tracko/commons/core/Messages.java
  src/main/java/tracko/logic/commands/item/EditItemCommand.java
  src/main/java/tracko/logic/parser/TrackOParser.java
  src/main/java/tracko/logic/parser/item/EditItemCommandParser.java
  src/main/java/tracko/model/Model.java
  src/main/java/tracko/model/ModelManager.java
  src/main/java/tracko/model/TrackO.java
  src/main/java/tracko/model/items/InventoryList.java
  src/main/java/tracko/model/items/Item.java
  src/main/java/tracko/model/items/exceptions/DuplicateItemException.java
  src/main/java/tracko/model/items/exceptions/ItemNotFoundException.java
  src/test/java/tracko/logic/commands/AddOrderCommandTest.java
Labels: priority.High, type.Story

#87 Fix UI Bugs
  src/main/java/tracko/logic/commands/item/AddItemCommand.java
  src/main/java/tracko/logic/commands/item/DeleteItemCommand.java
  src/main/java/tracko/logic/commands/order/AddOrderCommand.java
  src/main/java/tracko/logic/commands/order/DeleteOrderCommand.java
  src/main/java/tracko/model/items/Item.java
  src/main/java/tracko/ui/UiManager.java
  src/main/resources/images/track_o_logo.png
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/OrderListCard.fxml
  src/main/resources/view/TrackOTheme.css
Labels: type.Bug

#100 Implement test cases
  src/main/java/tracko/commons/core/Messages.java
  src/main/java/tracko/logic/commands/item/DeleteItemCommand.java
  src/main/java/tracko/logic/commands/order/DeleteOrderCommand.java
  src/main/java/tracko/model/ReadOnlyUserPrefs.java
  src/main/java/tracko/model/UserPrefs.java
  src/main/java/tracko/model/items/ItemName.java
  src/main/java/tracko/model/items/Quantity.java
  src/test/java/tracko/logic/commands/CommandTestUtil.java
  src/test/java/tracko/logic/commands/DeleteItemCommandTest.java
  src/test/java/tracko/logic/commands/DeleteOrderCommandTest.java
  src/test/java/tracko/model/items/DescriptionTest.java
  src/test/java/tracko/model/items/ItemContainsKeywordsPredicateTest.java
  src/test/java/tracko/model/items/ItemNameTest.java
  src/test/java/tracko/model/items/QuantityTest.java
  src/test/java/tracko/model/person/OrderContainsKeywordsPredicateTest.java
  src/test/java/tracko/testutil/ItemBuilder.java
  src/test/java/tracko/testutil/TypicalItems.java
Labels: priority.High

#104 Implement order completion status
  build.gradle
  docs/DeveloperGuide.md
  docs/SettingUp.md
  src/main/java/tracko/logic/parser/order/AddOrderCommandParser.java
  src/main/java/tracko/model/items/Quantity.java
  src/main/java/tracko/model/order/Order.java
  src/main/java/tracko/model/util/SampleDataUtil.java
  src/main/java/tracko/storage/JsonAdaptedOrder.java
  src/main/java/tracko/ui/OrderCard.java
  src/main/resources/view/OrderListCard.fxml
  src/main/resources/view/TrackOTheme.css
  src/test/java/tracko/storage/JsonAdaptedOrderTest.java
  src/test/java/tracko/testutil/OrderBuilder.java
Labels: priority.High, type.Story

#101 Implement item tags
  docs/UserGuide.md
  src/main/java/tracko/logic/commands/item/AddItemCommand.java
  src/main/java/tracko/logic/commands/item/EditItemCommand.java
  src/main/java/tracko/logic/parser/item/AddItemCommandParser.java
  src/main/java/tracko/storage/JsonAdaptedItem.java
  src/main/java/tracko/ui/ItemCard.java
  src/main/resources/view/ItemListCard.fxml
  src/main/resources/view/TrackOTheme.css
Labels: priority.High, type.Task, severity.Medium

#103 Add pricing
  docs/UserGuide.md
  src/main/java/tracko/commons/util/StringUtil.java
  src/main/java/tracko/logic/commands/item/AddItemCommand.java
  src/main/java/tracko/logic/commands/item/EditItemCommand.java
  src/main/java/tracko/logic/parser/CliSyntax.java
  src/main/java/tracko/logic/parser/ParserUtil.java
  src/main/java/tracko/logic/parser/item/AddItemCommandParser.java
  src/main/java/tracko/logic/parser/order/FindOrderCommandParser.java
  src/main/java/tracko/model/items/Item.java
  src/main/java/tracko/model/items/Price.java
  src/main/java/tracko/model/items/Quantity.java
  src/main/java/tracko/storage/JsonAdaptedItem.java
  src/main/java/tracko/ui/ItemCard.java
  src/main/resources/view/ItemListCard.fxml
  src/main/resources/view/TrackOTheme.css
  src/test/java/tracko/testutil/ItemBuilder.java
  src/test/java/tracko/testutil/OrderBuilder.java
  src/test/java/tracko/testutil/TypicalItems.java
Labels: priority.High, type.Story, severity.Medium

#108 Implement sort orders + date/time field for Orders in UI and Storage
  docs/UserGuide.md
  src/main/java/tracko/commons/core/Messages.java
  src/main/java/tracko/commons/util/DateTimeUtil.java
  src/main/java/tracko/logic/Logic.java
  src/main/java/tracko/logic/LogicManager.java
  src/main/java/tracko/logic/commands/order/DeleteOrderCommand.java
  src/main/java/tracko/logic/commands/order/SortOrderCommand.java
  src/main/java/tracko/logic/parser/TrackOParser.java
  src/main/java/tracko/logic/parser/order/FindOrderCommandParser.java
  src/main/java/tracko/logic/parser/order/SortOrderCommandParser.java
  src/main/java/tracko/model/Model.java
  src/main/java/tracko/model/ModelManager.java
  src/main/java/tracko/model/order/Order.java
  src/main/java/tracko/model/order/OrderDateTimeComparator.java
  src/main/java/tracko/storage/JsonAdaptedOrder.java
  src/main/java/tracko/ui/MainWindow.java
  src/main/java/tracko/ui/OrderCard.java
  src/main/resources/view/OrderListCard.fxml
  src/main/resources/view/TrackOTheme.css
  src/test/java/tracko/logic/commands/AddOrderCommandTest.java
  src/test/java/tracko/storage/JsonAdaptedOrderTest.java
  src/test/java/tracko/testutil/OrderBuilder.java
Labels: priority.High, type.Story

#114 Update DG Edit Item Feature
  docs/DeveloperGuide.md
Labels: priority.High, type.Task

#111 Implement EditOrderCommand
  docs/UserGuide.md
  src/main/java/tracko/logic/commands/item/AddItemCommand.java
  src/main/java/tracko/logic/commands/item/DeleteItemCommand.java
  src/main/java/tracko/logic/commands/item/EditItemCommand.java
  src/main/java/tracko/logic/commands/order/EditOrderCommand.java
  src/main/java/tracko/logic/parser/TrackOParser.java
  src/main/java/tracko/logic/parser/item/EditItemCommandParser.java
  src/main/java/tracko/logic/parser/order/EditOrderCommandParser.java
  src/main/java/tracko/model/Model.java
  src/main/java/tracko/model/ModelManager.java
  src/main/java/tracko/model/TrackO.java
  src/main/java/tracko/model/item/InventoryList.java
  src/main/java/tracko/model/item/Item.java
  src/main/java/tracko/model/item/ItemName.java
  src/main/java/tracko/model/order/Order.java
  src/main/java/tracko/model/order/OrderList.java
  src/main/java/tracko/model/util/SampleDataUtil.java
  src/main/java/tracko/ui/ItemCard.java
  src/main/java/tracko/ui/MainWindow.java
  src/main/java/tracko/ui/OrderCard.java
  src/main/java/tracko/ui/ResultDisplay.java
  src/main/resources/view/ItemListCard.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/OrderListCard.fxml
  src/main/resources/view/TrackOTheme.css
  src/test/java/tracko/logic/commands/AddOrderCommandTest.java
  src/test/java/tracko/testutil/EditOrderDescriptorBuilder.java
  src/test/java/tracko/testutil/OrderUtil.java
Labels: priority.High, type.Story

#117 Fixed Item price implementation
  src/main/java/tracko/logic/parser/ParserUtil.java
  src/main/java/tracko/model/item/Item.java
  src/main/java/tracko/model/item/Price.java
  src/main/java/tracko/model/util/SampleDataUtil.java
  src/main/java/tracko/storage/JsonAdaptedItem.java
  src/main/java/tracko/ui/ItemCard.java
  src/test/java/tracko/logic/commands/AddOrderCommandIntegrationTest.java
  src/test/java/tracko/model/order/ItemQuantityPairTest.java
  src/test/java/tracko/model/order/OrderContainsKeywordsPredicateTest.java
  src/test/java/tracko/storage/JsonTrackOStorageTest.java
  src/test/java/tracko/testutil/ItemBuilder.java
  src/test/java/tracko/testutil/TypicalItems.java
Labels: priority.High, type.Bug

#118 Add marko feature functionality
  src/main/java/tracko/commons/core/Messages.java
  src/main/java/tracko/logic/commands/item/EditItemCommand.java
  src/main/java/tracko/logic/commands/order/MarkOrderCommand.java
  src/main/java/tracko/logic/parser/ArgumentMultimap.java
  src/main/java/tracko/logic/parser/ArgumentToken.java
  src/main/java/tracko/logic/parser/CliSyntax.java
  src/main/java/tracko/logic/parser/Flag.java
  src/main/java/tracko/logic/parser/FlagTokenizer.java
  src/main/java/tracko/logic/parser/Prefix.java
  src/main/java/tracko/logic/parser/TrackOParser.java
  src/main/java/tracko/logic/parser/order/MarkOrderCommandParser.java
  src/main/java/tracko/model/item/Item.java
  src/main/java/tracko/storage/JsonAdaptedItem.java
  src/main/java/tracko/ui/ItemCard.java
  src/test/java/tracko/logic/commands/EditPersonDescriptorTest.java
  src/test/java/tracko/logic/commands/MarkOrderCommandTest.java
  src/test/java/tracko/logic/parser/FlagTokenizerTest.java
  src/test/java/tracko/logic/parser/MarkOrderCommandParserTest.java
  src/test/java/tracko/testutil/ItemBuilder.java
Labels: priority.High, type.Story

#120 Update editi for editing item price
  src/main/java/tracko/logic/commands/item/AddItemCommand.java
  src/main/java/tracko/logic/commands/item/EditItemCommand.java
  src/main/java/tracko/logic/parser/item/EditItemCommandParser.java
  src/main/java/tracko/model/item/Item.java
Labels: priority.High, type.Bug, severity.High

#121 Add functionality to verify stock for delivery
  src/main/java/tracko/commons/core/Messages.java
  src/main/java/tracko/logic/commands/order/MarkOrderCommand.java
  src/main/java/tracko/model/Model.java
  src/main/java/tracko/model/ModelManager.java
  src/main/java/tracko/model/item/Item.java
  src/main/java/tracko/model/order/Order.java
  src/test/java/tracko/logic/commands/AddOrderCommandTest.java
Labels: priority.High, type.Story

#130 Implement listi, findi, and FindItemCommandParser tests
  src/test/java/logic/LogicManagerTest.java
  src/test/java/logic/commands/AddOrderCommandIntegrationTest.java
  src/test/java/logic/commands/AddOrderCommandTest.java
  src/test/java/logic/commands/ClearCommandTest.java
  src/test/java/logic/commands/CommandResultTest.java
  src/test/java/logic/commands/CommandTestUtil.java
  src/test/java/logic/commands/DeleteItemCommandTest.java
  src/test/java/logic/commands/DeleteOrderCommandTest.java
  src/test/java/logic/commands/EditOrderCommandTest.java
  src/test/java/logic/commands/EditOrderDescriptorTest.java
  src/test/java/logic/commands/ExitCommandTest.java
  src/test/java/logic/commands/FindCommandTest.java
  src/test/java/logic/commands/FindItemCommandTest.java
  src/test/java/logic/commands/HelpCommandTest.java
  src/test/java/logic/commands/ListItemsCommandTest.java
  src/test/java/logic/commands/ListOrdersCommandTest.java
  src/test/java/logic/commands/MarkOrderCommandTest.java
  src/test/java/logic/parser/AddOrderCommandParserTest.java
  src/test/java/logic/parser/ArgumentTokenizerTest.java
  src/test/java/logic/parser/CommandParserTestUtil.java
  src/test/java/logic/parser/DeleteOrderCommandParserTest.java
  src/test/java/logic/parser/EditOrderCommandParserTest.java
  src/test/java/logic/parser/FindItemCommandParserTest.java
  src/test/java/logic/parser/FindOrderCommandParserTest.java
  src/test/java/logic/parser/FlagTokenizerTest.java
  src/test/java/logic/parser/MarkOrderCommandParserTest.java
  src/test/java/logic/parser/ParserUtilTest.java
  src/test/java/logic/parser/TrackOParserTest.java
  src/test/java/tracko/logic/commands/EditOrderDescriptorTest.java
  src/test/java/tracko/logic/commands/FindCommandTest.java
  src/test/java/tracko/logic/commands/ListItemsCommandTest.java
  src/test/java/tracko/testutil/TypicalOrders.java
Labels: priority.High, type.Test

#125 Update functionality of findo to be more powerful
  src/main/java/tracko/commons/core/Messages.java
  src/main/java/tracko/commons/util/StringUtil.java
  src/main/java/tracko/logic/commands/order/FindOrderCommand.java
  src/main/java/tracko/logic/parser/ArgumentMultimap.java
  src/main/java/tracko/logic/parser/CliSyntax.java
  src/main/java/tracko/logic/parser/order/FindOrderCommandParser.java
  src/main/java/tracko/logic/parser/order/MarkOrderCommandParser.java
  src/main/java/tracko/model/item/Price.java
  src/main/java/tracko/model/order/OrderContainsKeywordsPredicate.java
  src/main/java/tracko/model/order/OrderMatchesFlagsAndPrefixPredicate.java
  src/test/java/logic/commands/CommandTestUtil.java
  src/test/java/logic/parser/FindOrderCommandParserTest.java
  src/test/java/tracko/model/order/OrderContainsKeywordsPredicateTest.java
Labels: priority.Medium, type.Enhancement

#127 Move method to item quantity in inventory
  src/main/java/tracko/model/ModelManager.java
  src/main/java/tracko/model/TrackO.java
  src/main/java/tracko/model/item/InventoryList.java
Labels: type.Bug, severity.Low

#128 Update edit order test
  src/test/java/logic/commands/EditOrderCommandTest.java
  src/test/java/tracko/testutil/OrderBuilder.java
  src/test/java/tracko/testutil/TypicalOrders.java
Labels: priority.High, type.Bug, type.Test

#131 Calculate ordered items price
  src/main/java/tracko/model/item/Price.java
  src/main/java/tracko/model/order/ItemQuantityPair.java
  src/main/java/tracko/model/order/Order.java
  src/main/java/tracko/model/order/OrderList.java
  src/main/java/tracko/model/util/SampleDataUtil.java
  src/main/java/tracko/ui/ItemCard.java
  src/main/java/tracko/ui/OrderCard.java
  src/main/resources/view/ItemListCard.fxml
  src/main/resources/view/OrderListCard.fxml
  src/main/resources/view/TrackOTheme.css
  src/test/java/tracko/logic/LogicManagerTest.java
  src/test/java/tracko/logic/commands/AddOrderCommandIntegrationTest.java
  src/test/java/tracko/logic/commands/AddOrderCommandTest.java
  src/test/java/tracko/logic/commands/ClearCommandTest.java
  src/test/java/tracko/logic/commands/CommandResultTest.java
  src/test/java/tracko/logic/commands/CommandTestUtil.java
  src/test/java/tracko/logic/commands/DeleteItemCommandTest.java
  src/test/java/tracko/logic/commands/DeleteOrderCommandTest.java
  src/test/java/tracko/logic/commands/EditOrderCommandTest.java
  src/test/java/tracko/logic/commands/EditOrderDescriptorTest.java
  src/test/java/tracko/logic/commands/ExitCommandTest.java
  src/test/java/tracko/logic/commands/FindCommandTest.java
  src/test/java/tracko/logic/commands/FindItemCommandTest.java
  src/test/java/tracko/logic/commands/HelpCommandTest.java
  src/test/java/tracko/logic/commands/ListItemsCommandTest.java
  src/test/java/tracko/logic/commands/ListOrdersCommandTest.java
  src/test/java/tracko/logic/commands/MarkOrderCommandTest.java
  src/test/java/tracko/logic/parser/AddItemCommandParserTest.java
  src/test/java/tracko/logic/parser/AddOrderCommandParserTest.java
  src/test/java/tracko/logic/parser/ArgumentTokenizerTest.java
  src/test/java/tracko/logic/parser/CommandParserTestUtil.java
  src/test/java/tracko/logic/parser/DeleteItemCommandParserTest.java
  src/test/java/tracko/logic/parser/DeleteOrderCommandParserTest.java
  src/test/java/tracko/logic/parser/EditOrderCommandParserTest.java
  src/test/java/tracko/logic/parser/FindItemCommandParserTest.java
  src/test/java/tracko/logic/parser/FindOrderCommandParserTest.java
  src/test/java/tracko/logic/parser/FlagTokenizerTest.java
  src/test/java/tracko/logic/parser/MarkOrderCommandParserTest.java
  src/test/java/tracko/logic/parser/ParserUtilTest.java
  src/test/java/tracko/logic/parser/TrackOParserTest.java
  src/test/java/tracko/model/order/ItemQuantityPairTest.java
  src/test/java/tracko/model/order/OrderTest.java
  src/test/java/tracko/testutil/TypicalOrders.java
Labels: priority.High, type.Story

#123 Fix bug and add tests
  src/main/java/tracko/logic/commands/order/MarkOrderCommand.java
  src/test/java/tracko/logic/commands/CommandTestUtil.java
  src/test/java/tracko/logic/commands/DeleteOrderCommandTest.java
  src/test/java/tracko/logic/commands/EditItemCommandTest.java
  src/test/java/tracko/logic/commands/SortOrderCommandTest.java
  src/test/java/tracko/logic/parser/AddItemCommandParserTest.java
  src/test/java/tracko/logic/parser/AddOrderCommandParserTest.java
  src/test/java/tracko/testutil/EditItemDescriptorBuilder.java
  src/test/java/tracko/testutil/ItemBuilder.java
Labels: priority.High, type.Task, type.Bug, severity.High

#139 Finalize UI
  src/main/java/tracko/logic/commands/order/EditOrderCommand.java
  src/main/java/tracko/ui/ItemCard.java
  src/main/java/tracko/ui/OrderCard.java
  src/main/java/tracko/ui/OrderListPanel.java
  src/main/resources/view/ItemListCard.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/OrderListCard.fxml
  src/main/resources/view/TrackOTheme.css
Labels: priority.High, type.Enhancement, type.Bug

#137 Add UML diagram for EditItem in DG + changes to DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/developer-guide/ArchitectureSequenceDiagram.puml
  docs/diagrams/developer-guide/BetterModelClassDiagram.puml
  docs/diagrams/developer-guide/DeleteItemSequenceDiagram.puml
  docs/diagrams/developer-guide/EditItemSequenceDiagram.puml
  docs/diagrams/developer-guide/LogicClassDiagram.puml
  docs/diagrams/developer-guide/ModelClassDiagram.puml
  docs/diagrams/developer-guide/StorageClassDiagram.puml
  docs/diagrams/developer-guide/UiClassDiagram.puml
  docs/images/developer-guide/ArchitectureSequenceDiagram.png
  docs/images/developer-guide/BetterModelClassDiagram.png
  docs/images/developer-guide/DeleteItemSequenceDiagram.png
  docs/images/developer-guide/EditItemSequenceDiagram.png
  docs/images/developer-guide/LogicClassDiagram.png
  docs/images/developer-guide/ModelClassDiagram.png
  docs/images/developer-guide/StorageClassDiagram.png
  docs/images/developer-guide/UiClassDiagram.png
Labels: priority.High, type.Task

#143 Add latest Ui.png
  docs/images/Ui.png
Labels: priority.High, type.Bug

#141 Update DG for add order command
  docs/DeveloperGuide.md
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/developer-guide/AddOrderActivityDiagram.puml
  docs/diagrams/developer-guide/AddOrderSequenceDiagram.puml
  docs/diagrams/developer-guide/AddOrderSequenceDiagram1.puml
  docs/diagrams/developer-guide/AddOrderSequenceDiagram2.puml
  docs/diagrams/developer-guide/AddOrderSequenceDiagram3.puml
  docs/diagrams/developer-guide/AddOrderState0.puml
  docs/diagrams/developer-guide/AddOrderState1.puml
  docs/diagrams/developer-guide/AddOrderState2a.puml
  docs/diagrams/developer-guide/AddOrderState2b.puml
  docs/diagrams/developer-guide/AddOrderState3.puml
  docs/diagrams/developer-guide/AddOrderState4.puml
  docs/diagrams/developer-guide/OrderClassDiagram.puml
  docs/diagrams/developer-guide/style.puml
  docs/images/developer-guide/AddOrderSequenceDiagram.png
  docs/images/developer-guide/AddOrderSequenceDiagram1.png
  docs/images/developer-guide/AddOrderSequenceDiagram2.png
  docs/images/developer-guide/AddOrderSequenceDiagram3.png
  docs/images/developer-guide/AddOrderState0.png
  docs/images/developer-guide/AddOrderState1.png
  docs/images/developer-guide/AddOrderState2a.png
  docs/images/developer-guide/AddOrderState2b.png
  docs/images/developer-guide/AddOrderState3.png
  docs/images/developer-guide/AddOrderState4.png
  docs/images/developer-guide/OrderClassDiagram.png
Labels: priority.High, type.Task, type.Documentation

#144 Update UG for marko and clear
  docs/UserGuide.md
Labels: type.Documentation

#147 Add help command to user guide
  docs/UserGuide.md
Labels: type.Task, type.Documentation

#191 Fix extra order panels
  src/main/java/tracko/ui/OrderListPanel.java
  src/main/resources/view/TrackOTheme.css
Labels: priority.High, type.Bug, severity.High, type.FunctionalityBug
