Repository AY2223S1-CS2103T-W15-3/tp, pull requests merged in 2022-11, with the labels that each got.

#190 Fix UI tags
  docs/UserGuide.md
  src/main/java/tracko/model/tag/Tag.java
  src/main/java/tracko/ui/ItemCard.java
  src/main/resources/view/ItemListCard.fxml
Labels: priority.High, type.Bug, type.FunctionalityBug

#187 Disallow editing of items with ongoing orders
  docs/UserGuide.md
  src/main/java/tracko/logic/commands/item/DeleteItemCommand.java
  src/main/java/tracko/logic/commands/item/EditItemCommand.java
  src/main/java/tracko/model/TrackO.java
  src/main/java/tracko/model/item/exceptions/ItemUnmodifiableException.java
  src/test/java/tracko/logic/commands/item/EditItemCommandTest.java
  src/test/java/tracko/testutil/OrderBuilder.java
Labels: priority.High, type.Bug, severity.High, type.FunctionalityBug

#188 Update error message and UG to indicate that tag should be 1 word
  docs/UserGuide.md
  src/main/java/tracko/model/tag/Tag.java
Labels: priority.High, type.Bug, type.DocumentationBug

#189 Update to indicate ItemName should be more than 1 character long
  docs/UserGuide.md
  src/main/java/tracko/model/item/ItemName.java
Labels: type.Bug, severity.High, type.DocumentationBug

#192 Fix price parsing errors & context menu readability
  src/main/java/tracko/logic/parser/ParserUtil.java
  src/main/java/tracko/model/item/Price.java
  src/main/java/tracko/model/item/Quantity.java
  src/main/java/tracko/ui/ItemCard.java
  src/main/resources/view/TrackOTheme.css
Labels: type.Bug, severity.High, type.FunctionalityBug

#193 UG restructure
  docs/UserGuide.md
Labels: priority.High, type.Documentation

#200 Add PPP
  docs/team/donljh.md
Labels: priority.High, type.Documentation

#202 Add PPP Enze
  docs/team/sohenze.md
  src/main/java/tracko/logic/commands/item/EditItemCommand.java
Labels: priority.High, type.Documentation

#207 Add PPP
  docs/DeveloperGuide.md
  docs/_sass/minima/_base.scss
  docs/_sass/minima/initialize.scss
  docs/team/melissaharijanto.md
  src/main/java/tracko/model/util/SampleDataUtil.java
Labels: priority.High, type.Documentation

#212 Update user guide with images
  docs/UserGuide.md
  docs/_sass/minima/custom-styles.scss
  docs/images/user-guide/AddiExample.png
  docs/images/user-guide/AddoExample1.png
  docs/images/user-guide/Clear.png
  docs/images/user-guide/DeleteiExample1.png
  docs/images/user-guide/DeleteiExample2.png
  docs/images/user-guide/DeleteoExample1.png
  docs/images/user-guide/DeleteoExample2-1.png
  docs/images/user-guide/DeleteoExample2-2.png
  docs/images/user-guide/DeleteoExample2-3.png
  docs/images/user-guide/DeleteoExample3-1.png
  docs/images/user-guide/DeleteoExample3-2.png
  docs/images/user-guide/EditiExample1.png
  docs/images/user-guide/EditiExample2.png
  docs/images/user-guide/EditiExample3.png
  docs/images/user-guide/EditiExample4.png
  docs/images/user-guide/EditoExample1-1.png
  docs/images/user-guide/EditoExample1-2.png
  docs/images/user-guide/EditoExample1-3.png
  docs/images/user-guide/EditoExample1-4.png
  docs/images/user-guide/FindiExample1.png
  docs/images/user-guide/FindiExample2.png
  docs/images/user-guide/FindoExample1.png
  docs/images/user-guide/FindoExample2.png
  docs/images/user-guide/FindoExample3.png
  docs/images/user-guide/FindoExample4.png
  docs/images/user-guide/Help.png
  docs/images/user-guide/HomeFolder.png
  docs/images/user-guide/ListiExample.png
  docs/images/user-guide/ListoExample.png
  docs/images/user-guide/MarkoExample1.png
  docs/images/user-guide/MarkoExample2.png
  docs/images/user-guide/SortoNew1-1.png
  docs/images/user-guide/SortoNew1-2.png
  docs/images/user-guide/SortoNew1-3.png
  docs/images/user-guide/SortoOldExample.png
  docs/images/user-guide/TrackOLayout.png
  docs/images/user-guide/Tutorial1.png
  docs/images/user-guide/Tutorial2.png
  docs/images/user-guide/Tutorial3.png
  docs/images/user-guide/Tutorial4.png
Labels: priority.High, type.Documentation

#211 Update add item implementation segment
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ArchitectureDiagram.puml
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/ComponentManagers.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/diagrams/developer-guide/AddItemActivityDiagram.puml
  docs/diagrams/developer-guide/AddItemSequenceDiagram.puml
  docs/diagrams/developer-guide/AddItemState0.puml
  docs/diagrams/developer-guide/AddItemState1.puml
  docs/diagrams/developer-guide/LogicClassDiagram.puml
  docs/diagrams/developer-guide/StorageClassDiagram.puml
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/images/UndoSequenceDiagram.png
  docs/images/developer-guide/AddItemActivityDiagram.png
  docs/images/developer-guide/AddItemSequenceDiagram.png
  docs/images/developer-guide/AddItemState0.png
  docs/images/developer-guide/AddItemState1.png
  docs/images/developer-guide/AddOrderState0.png
  docs/images/developer-guide/AddOrderState1.png
  docs/images/developer-guide/AddOrderState2a.png
  docs/images/developer-guide/AddOrderState2b.png
  docs/images/developer-guide/AddOrderState3.png
  docs/images/developer-guide/AddOrderState4.png
  docs/images/developer-guide/LogicClassDiagram.png
  docs/images/developer-guide/StorageClassDiagram.png
Labels: priority.High, type.Documentation

#215 Add tests for EditItemCommandParser
  src/test/java/tracko/logic/parser/EditItemCommandParserTest.java
Labels: type.Test

#221 Update PPP (small changes)
  docs/team/melissaharijanto.md
Labels: type.Documentation

#209 Implement tests
  build.gradle
  docs/UserGuide.md
  docs/_sass/minima/custom-styles.scss
  docs/team/janelleljt.md
  src/main/java/tracko/model/item/Quantity.java
  src/test/java/tracko/logic/commands/CommandTestUtil.java
  src/test/java/tracko/logic/commands/HelpCommandTest.java
  src/test/java/tracko/logic/commands/item/DeleteItemCommandTest.java
  src/test/java/tracko/logic/parser/DeleteOrderCommandParserTest.java
  src/test/java/tracko/logic/parser/FindItemCommandParserTest.java
  src/test/java/tracko/logic/parser/FindOrderCommandParserTest.java
  src/test/java/tracko/model/item/PriceTest.java
  src/test/java/tracko/model/order/AddressTest.java
  src/test/java/tracko/model/order/EmailTest.java
  src/test/java/tracko/model/order/NameTest.java
  src/test/java/tracko/model/order/OrderDateTimeComparatorTest.java
  src/test/java/tracko/model/order/OrderMatchesFlagsAndPrefixPredicateTest.java
  src/test/java/tracko/model/order/PhoneTest.java
  src/test/java/tracko/testutil/OrderBuilder.java
Labels: priority.Medium

#213 Add tests for clear feature
  src/main/java/tracko/logic/commands/ClearCommand.java
  src/main/java/tracko/logic/parser/ClearCommandParser.java
  src/test/java/tracko/logic/commands/ClearCommandTest.java
  src/test/java/tracko/logic/commands/order/EditOrderCommandTest.java
  src/test/java/tracko/logic/commands/order/ListOrdersCommandTest.java
  src/test/java/tracko/logic/commands/order/MarkOrderCommandTest.java
  src/test/java/tracko/logic/parser/ClearCommandParserTest.java
  src/test/java/tracko/logic/parser/FindItemCommandParserTest.java
  src/test/java/tracko/logic/parser/FindOrderCommandParserTest.java
  src/test/java/tracko/logic/parser/MarkOrderCommandParserTest.java
Labels: type.Test

#223 Convert ArgumentToken wrapper class into an Interface
  src/main/java/tracko/logic/parser/ArgumentToken.java
  src/main/java/tracko/logic/parser/ArgumentTokenizer.java
  src/main/java/tracko/logic/parser/Flag.java
  src/main/java/tracko/logic/parser/FlagTokenizer.java
  src/main/java/tracko/logic/parser/Prefix.java
Labels: priority.Medium, type.Enhancement

#217 DG changes
  docs/DeveloperGuide.md
  docs/diagrams/developer-guide/DeleteItemSequenceDiagram.puml
  docs/diagrams/developer-guide/EditItemSequenceDiagram.puml
  docs/diagrams/developer-guide/ModelClassDiagram.puml
  docs/diagrams/developer-guide/ParserClasses.puml
  docs/images/developer-guide/DeleteItemSequenceDiagram.png
  docs/images/developer-guide/EditItemSequenceDiagram.png
  docs/images/developer-guide/ModelClassDiagram.png
  docs/images/developer-guide/ParserClasses.png
  docs/team/sohenze.md
Labels: priority.High, type.Documentation, type.DocumentationBug

#227 Update PPP
  docs/team/sohenze.md
Labels: priority.High, type.Documentation

#224 Dg testing instructions
  docs/DeveloperGuide.md
  docs/diagrams/developer-guide/FindOrderActivityDiagram.puml
  docs/images/FindOrderActivityDiagram.png
  docs/team/janelleljt.md
Labels: priority.High

#225 Edit developer guide and user guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/melissaharijanto.md
Labels: type.Documentation

#231 Add page breaks to UG
  docs/UserGuide.md
Labels: priority.Medium, type.Documentation

#233 Add page break DG
  docs/DeveloperGuide.md
Labels: priority.Medium, type.Documentation
